### ISSUE TITLE
PR: Add `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [dustinspecker/awesome-flow#1]
This plugin reports flow errors as ESLint errors.
Here's a demo:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

https://github.com/amilajack/eslint-plugin-flowtype-errors

**Comment by dustinspecker** [comment]
Thank you! This looks great! I've added it in b41b5a7f99cb9f98cf63c368163ea41d78aba84d.
